repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: check-case-conflict
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [--line-length=100]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length=100"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=100", "--extend-ignore=E203"]
        additional_dependencies: [
            'flake8-docstrings',
            'flake8-bugbear',
        ]

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.3.0
#    hooks:
#    -   id: mypy
#        additional_dependencies: [
#            'types-PyYAML',
#            'types-requests',
#            'torch',
#        ]

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    -   id: nbqa-black
        args: [--line-length=100]
    #-   id: nbqa-isort
        #args: ["--profile", "~/.local/bi/black", "--line-length=100"]
    -   id: nbqa-flake8
        args: ["--max-line-length=100", "--extend-ignore=E203"]

-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout
        args: ["--extra-keys", "metadata.kernelspec"] 